pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: DockerHub

steps:
  - task: JavaToolInstaller@0
    inputs:
      versionSpec: '17'
      jdkArchitectureOption: 'x64'
      jdkSourceOption: 'PreInstalled'
    displayName: 'Install Java17'

  - script: |
      java --version
    displayName: 'Check Java version'

  - script: |
      mvn clean package
    workingDirectory: FruitAndStockServices
    displayName: 'Create jar'

  - script: |
      tag=$(git rev-parse --short HEAD)
      docker build --tag aggregator:$tag .
      docker images | grep aggregator
    workingDirectory: FruitAndStockServices/FruitShop
    displayName: 'Create docker image'

  - script: |
      tag=$(git rev-parse --short HEAD)
      docker tag aggregator:$tag zsofiaelek/fruitshop:$tag
      docker login docker.io -u $(dockeruser) -p $(dockerpw)
      docker push zsofiaelek/fruitshop:$tag
    displayName: 'Upload docker image'
    

