pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: JavaToolInstaller@0
    inputs:
      versionSpec: '17'
      jdkArchitectureOption: 'x64'
      jdkSourceOption: 'PreInstalled'
    displayName: 'Install Java17'

  - script: |
      java --version
    displayName: 'Check Java version'

  - script: |
      chmod 745 ./mvnw.cmd
    displayName: 'Set permission for folder'

  - script: |
      ./mvnw clean package
    workingDirectory: FruitAndStockServices
    displayName: 'Create jar'

