pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: DockerHub

steps:
  - task: JavaToolInstaller@0
    inputs:
      versionSpec: '17'
      jdkArchitectureOption: 'x64'
      jdkSourceOption: 'PreInstalled'
    displayName: 'Install Java17'

  - script: |
      java --version
    displayName: 'Check Java version'

  - script: |
      mvn clean package
    workingDirectory: FruitAndStockServices
    displayName: 'Create jar'

  - script: |
      docker login docker.io -u $(dockeruser) -p $(dockerpw)
    displayName: 'Login to Docker Hub'

  - script: |
      tag=fruitshop-$(git rev-parse --short HEAD)
      docker build --tag zsofiaelek/fruitshop:$tag .
      docker push zsofiaelek/fruitshop:$tag
    workingDirectory: FruitAndStockServices/FruitShop
    displayName: 'Create and push fruitshop docker image'

  - script: |
      tag=fruitmock-$(git rev-parse --short HEAD)
      docker build --tag zsofiaelek/fruitshop:$tag .
      docker push zsofiaelek/fruitshop:$tag
    workingDirectory: FruitAndStockServices/FruitMockService
    displayName: 'Create and push fruitmock docker image'

  - script: |
      tag=stockmock-$(git rev-parse --short HEAD)
      docker build --tag zsofiaelek/fruitshop:$tag .
      docker push zsofiaelek/fruitshop:$tag
    workingDirectory: FruitAndStockServices/StockMockService
    displayName: 'Create and push stockmock docker image'






