apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: fruitshop-hpa
  namespace: fruit
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fruitshop-deployment
  minReplicas: 3
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50